<a href="https://colab.research.google.com/github/kalyani-m-g/saiket/blob/main/saiket_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
#Task 1: Data Preparation

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Telco_Customer_Churn_Dataset  (1).csv to Telco_Customer_Churn_Dataset  (1).csv

In [3]:
df = pd.read_csv("Telco_Customer_Churn_Dataset  (1).csv")

In [5]:
df.shape

(7043, 21)

In [6]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [4]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [8]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [13]:
df["Churn"].unique()

array(['No', 'Yes'], dtype=object)

In [14]:
df["Churn"] = df["Churn"].map({"Yes": 1, "No": 0})

In [15]:
df.drop("customerID", axis=1, inplace=True)

In [16]:
df = pd.get_dummies(df, drop_first=True)

In [17]:
df.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,0,False,True,False,False,True,...,False,False,False,False,False,False,True,False,True,False
1,0,34,56.95,1889.50,0,True,False,False,True,False,...,False,False,False,False,True,False,False,False,False,True
2,0,2,53.85,108.15,1,True,False,False,True,False,...,False,False,False,False,False,False,True,False,False,True
3,0,45,42.30,1840.75,0,True,False,False,False,True,...,False,False,False,False,True,False,False,False,False,False
4,0,2,70.70,151.65,1,False,False,False,True,False,...,False,False,False,False,False,False,True,False,True,False

In [18]:
df.to_csv("Preprocessed_Churn_Data.csv", index=False)

In [28]:
##task1 report:The Telco Customer Churn dataset was loaded into Google Colab and examined using Pandas functions. Missing values were checked and none were found in the dataset. The target variable `Churn` was converted into numerical format (Yes = 1, No = 0). The `customerID` column was removed as it is not useful for prediction. Categorical variables were encoded into numerical values using one-hot encoding. The dataset was successfully preprocessed and made ready for machine learning tasks.

In [20]:
#Task 2: Split Data for Training and Testing.

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X = df.drop("Churn", axis=1)
y = df["Churn"]

In [23]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [24]:
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

X_train shape: (5634, 30)
y_train shape: (5634,)

In [25]:
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

X_test shape: (1409, 30)
y_test shape: (1409,)

In [26]:
print(y_train.value_counts(normalize=True))
print(y_test.value_counts(normalize=True))

Churn
0    0.734647
1    0.265353
Name: proportion, dtype: float64
Churn
0    0.734564
1    0.265436
Name: proportion, dtype: float64

In [27]:
#task 2 report: The dataset was successfully divided into training and testing sets using an 80:20 ratio. Stratified sampling was applied to maintain the original distribution of the target variable (Churn) in both datasets. The training set contained approximately 73.46% non-churn customers and 26.54% churn customers, while the testing set showed a nearly identical distribution. This ensures representative data for model training and evaluation.

In [29]:
#TASK 3: FEATURE SELECTION

In [30]:
correlation = df.corr()["Churn"].sort_values(ascending=False)
print(correlation)

Churn                                    1.000000
InternetService_Fiber optic              0.308020
PaymentMethod_Electronic check           0.301919
MonthlyCharges                           0.193356
PaperlessBilling_Yes                     0.191825
SeniorCitizen                            0.150889
StreamingTV_Yes                          0.063228
StreamingMovies_Yes                      0.061382
MultipleLines_Yes                        0.040102
PhoneService_Yes                         0.011942
gender_Male                             -0.008612
MultipleLines_No phone service          -0.011942
DeviceProtection_Yes                    -0.066160
OnlineBackup_Yes                        -0.082255
PaymentMethod_Mailed check              -0.091683
PaymentMethod_Credit card (automatic)   -0.134302
Partner_Yes                             -0.150448
Dependents_Yes                          -0.164221
TechSupport_Yes                         -0.164674
OnlineSecurity_Yes                      -0.171226
Contract_One year                       -0.177820
TotalCharges                            -0.199484
InternetService_No                      -0.227890
StreamingTV_No internet service         -0.227890
OnlineSecurity_No internet service      -0.227890
OnlineBackup_No internet service        -0.227890
DeviceProtection_No internet service    -0.227890
StreamingMovies_No internet service     -0.227890
TechSupport_No internet service         -0.227890
Contract_Two year                       -0.302253
tenure                                  -0.352229
Name: Churn, dtype: float64

In [31]:
print(correlation.head(15))

Churn                             1.000000
InternetService_Fiber optic       0.308020
PaymentMethod_Electronic check    0.301919
MonthlyCharges                    0.193356
PaperlessBilling_Yes              0.191825
SeniorCitizen                     0.150889
StreamingTV_Yes                   0.063228
StreamingMovies_Yes               0.061382
MultipleLines_Yes                 0.040102
PhoneService_Yes                  0.011942
gender_Male                      -0.008612
MultipleLines_No phone service   -0.011942
DeviceProtection_Yes             -0.066160
OnlineBackup_Yes                 -0.082255
PaymentMethod_Mailed check       -0.091683
Name: Churn, dtype: float64

In [33]:
selected_features = [
    'tenure',
    'MonthlyCharges',
    'Contract_One year',
    'Contract_Two year',
    'OnlineSecurity_Yes',
    'TechSupport_Yes',
    'InternetService_Fiber optic',
    'PaperlessBilling_Yes'
]

In [34]:
X_selected = df[selected_features]
X_selected.head()

,tenure,MonthlyCharges,Contract_One year,Contract_Two year,OnlineSecurity_Yes,TechSupport_Yes,InternetService_Fiber optic,PaperlessBilling_Yes
0,1,29.85,False,False,False,False,False,True
1,34,56.95,True,False,True,False,False,False
2,2,53.85,False,False,True,False,False,True
3,45,42.30,True,False,True,True,False,False
4,2,70.70,False,False,False,False,True,True

In [35]:
print(X_selected.columns)

Index(['tenure', 'MonthlyCharges', 'Contract_One year', 'Contract_Two year',
       'OnlineSecurity_Yes', 'TechSupport_Yes', 'InternetService_Fiber optic',
       'PaperlessBilling_Yes'],
      dtype='object')

In [36]:
#task 3 report: Feature selection was performed to identify the attributes that significantly influence customer churn. Correlation analysis was used to examine the relationship between features and the target variable (Churn). Based on the analysis, important features such as tenure, monthly charges, contract type, online security, tech support, internet service type, and paperless billing were selected. These features were chosen for model training as they have a strong impact on customer churn prediction.

In [37]:
#TASK 4: MODEL SELECTION

In [38]:
from sklearn.linear_model import LogisticRegression

In [39]:
model = LogisticRegression(max_iter=1000)

In [40]:
print(model)

LogisticRegression(max_iter=1000)

In [41]:
#task 4 report: A suitable binary classification algorithm was selected for customer churn prediction. Logistic Regression was chosen because the target variable (Churn) has two classes: churn and non-churn. The algorithm is simple, efficient, and widely used for binary classification problems. It provides good performance and helps understand the relationship between customer attributes and churn behavior.

In [42]:
#TASK 5: MODEL TRAINING

In [44]:
model.fit(X_train[selected_features], y_train)

LogisticRegression(max_iter=1000)

In [45]:
print("Model trained successfully!")

Model trained successfully!

In [46]:
print(model.coef_)

[[-0.03306769  0.02435339 -0.84316286 -1.57212665 -0.51424861 -0.47515886
   0.28665034  0.48014597]]

In [47]:
y_pred = model.predict(X_test[selected_features])

In [48]:
print(y_pred[:10])

[0 1 0 0 0 1 1 0 0 0]

In [49]:
#task 5 report : The Logistic Regression model was trained using the training dataset. The selected features were used as input variables, and the Churn column was used as the target variable. The model learned patterns from historical customer data and was successfully fitted to the training set. After training, the model was used to generate predictions for customer churn on the testing dataset.

In [50]:
#TASK 6: MODEL EVALUATION

In [51]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

In [52]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred)

In [53]:
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)
print("ROC-AUC:", roc_auc)

Accuracy: 0.7799858055358411
Precision: 0.6038961038961039
Recall: 0.49732620320855614
F1-Score: 0.5454545454545454
ROC-AUC: 0.6897259035366452

In [54]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.88      0.85      1035
           1       0.60      0.50      0.55       374

    accuracy                           0.78      1409
   macro avg       0.72      0.69      0.70      1409
weighted avg       0.77      0.78      0.77      1409

In [55]:
#task 6 report : The performance of the Logistic Regression model was evaluated using the testing dataset. The model achieved an accuracy of 78%. For churn prediction, the precision was 60%, recall was 50%, and F1-score was 55%. The model performed well in identifying non-churn customers, with an F1-score of 85% for class 0. Overall, the model demonstrated satisfactory performance and can be used to predict customer churn with reasonable accuracy.

In [58]:
sample_customer = X_test[selected_features].iloc[[0]]

print("Actual:", y_test.iloc[0])
print("Predicted:", model.predict(sample_customer)[0])
print("Churn Probability:", model.predict_proba(sample_customer)[0][1])

Actual: 0
Predicted: 0
Churn Probability: 0.044036090158553136

In [59]:
#inference: A sample customer from the test dataset was given as input to the trained Logistic Regression model. The model predicted class 0 (No Churn) with a churn probability of 4.4%. The actual value was also 0, indicating that the prediction was correct. This demonstrates that the model can successfully classify customers based on their attributes and estimate the likelihood of churn.

In [61]:
#churn example
for i in range(len(X_test)):
    sample = X_test[selected_features].iloc[[i]]

    pred = model.predict(sample)[0]

    if pred == 1:
        print("Index:", i)
        print("Actual:", y_test.iloc[i])
        print("Predicted:", pred)
        print("Churn Probability:", model.predict_proba(sample)[0][1])
        break

Index: 1
Actual: 0
Predicted: 1
Churn Probability: 0.6870760492757119

In [62]:
#inference: A sample customer from the test dataset was evaluated using the trained Logistic Regression model. The model predicted that the customer would churn with a probability of 68.7%. However, the actual class was non-churn. This represents a false positive prediction, where the model incorrectly classified a customer as likely to churn. Such cases are expected in predictive models and are measured through evaluation metrics such as precision, recall, and F1-score.